
# currently does not work with frameworks!
#use_frameworks!

target 'FeedMediaUI_Example', :exclusive => true do
  pod 'FeedMediaUI', :path => '../'
end

target 'FeedMediaUI_Tests', :exclusive => true do
  pod 'FeedMediaUI', :path => '../'
end
