
source 'git@github.com:feedfm/cocoapod-repo.git'
source 'https://github.com/CocoaPods/Specs.git'

#use_frameworks!

target 'FeedMediaUI_Example', :exclusive => true do
  pod 'FeedMediaUI', :path => '../'
end

target 'FeedMediaUI_Tests', :exclusive => true do
  pod 'FeedMediaUI', :path => '../'
end
